name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  dte:
    runs-on: ubuntu-latest
    # only run this job if DTE is enabled
    if: vars.ENABLE_DTE == 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      - run: npx nx-cloud start-ci-run --distribute-on="3 default" --stop-agents-after="e2e-ci"

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build e2e
  non-dte:
    # machine size may need to be increased depending on workload size
    runs-on: ubuntu-latest
    # if DTE is not enabled, default back to this job
    if: vars.ENABLE_DTE != 'true'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build e2e
